//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CursoMateria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CursoMateria()
        {
            this.Final = new HashSet<Final>();
        }
    
        public int idCursoMateria { get; set; }
        public int idMateria { get; set; }
        public int Matricula { get; set; }
        public Nullable<int> PrimerParcial { get; set; }
        public Nullable<int> SegundoParcial { get; set; }
        public Nullable<int> TercerParcial { get; set; }
        public Nullable<int> PrimerRecuperatorio { get; set; }
        public Nullable<int> SegundoRecuperatorio { get; set; }
        public string Estado { get; set; }
        public Nullable<int> idDivision { get; set; }
        public Nullable<int> NotaFinal { get; set; }
        public string Inscripcion_EFinal { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual Materia Materia { get; set; }
        public virtual Division Division { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Final> Final { get; set; }
    }
}
